# -*- coding: utf-8 -*-
"""Quran.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WwaR-xsFnY5iffCndJV5metzB0RS4_GP
"""

import sqlite3
import re
from rapidfuzz.distance import Levenshtein

# ==========================================
# طبقة التطبيع الموسعة
# ==========================================

# مجموعات الحروف المتشابهة بصرياً أو صوتياً — كلها ترجع لشكل واحد
_SIMILAR_GROUPS = [
    ('اأإآٱ', 'ا'),
    ('ةه',   'ه'),
    ('يىئ',  'ي'),
    ('وؤ',   'و'),
    ('ذد',   'د'),   # متقاربة بصرياً للمبتدئين
    ('زرذ',  'ر'),   # أحياناً يخلط المستخدم بينها
    ('طت',   'ت'),
    ('ضظ',   'ض'),
    ('سص',   'س'),
    ('ثت',   'ت'),
    ('خح',   'ح'),
    ('غع',   'ع'),
]

def _build_similarity_table():
    table = {}
    for group, canonical in _SIMILAR_GROUPS:
        for ch in group:
            table[ch] = canonical
    return table

_SIM_TABLE = _build_similarity_table()

# Compiled regex patterns for input sanitization
_RE_INVISIBLE = re.compile(
    '[​-‏  ﻿­]'
)
_RE_SPACES = re.compile(
    '[  -   　]'
)
_PUNCT_CHARS = (
    '،؛؟'
    '!.,:;?\\-—–'
    '()\\[\\]{}«»'
    '﴾﴿⌈⌉❝❞'
    + chr(0x201C) + chr(0x201D) + chr(0x2018) + chr(0x2019)
    + chr(0x22) + chr(0x27) +
    'ـ'
    '۝؀-؃'
    '0-9٠-٩'
    '⁰¹²³⁴-⁹'
    'ﷺﷻﷲ'
    '#@&%\\^*+=/\\\\|~`_'
)
_RE_PUNCT = re.compile('[' + _PUNCT_CHARS + ']')
_RE_DIACRITICS = re.compile(
    '[ً-ٰٟٱٖ'
    'ۖ-ۜ۟-۪ۤۧۨ-ۭ]'
)

def normalize_arabic(text: str, *, deep: bool = False) -> str:
    """
    تطبيع النص العربي.
    deep=False  → تطبيع خفيف (للتخزين في DB أو المقارنة الدقيقة)
    deep=True   → تطبيع عميق يساوي بين الحروف المتشابهة (للبحث الضبابي)
    """
    if not text:
        return ""
    text = _RE_INVISIBLE.sub('', text)
    text = _RE_SPACES.sub(' ', text)
    text = _RE_PUNCT.sub('', text)
    text = _RE_DIACRITICS.sub('', text)
    text = re.sub(r'[أإآٱ]', 'ا', text)
    text = re.sub(r'ة', 'ه', text)
    text = re.sub(r'ى', 'ي', text)

    if deep:
        text = ''.join(_SIM_TABLE.get(ch, ch) for ch in text)

    return ' '.join(text.strip().split())


# ==========================================
# مطابقة ضبابية على مستوى الكلمات
# ==========================================

def _word_similarity(a: str, b: str) -> float:
    """نسبة التشابه بين كلمتين (0.0 → 1.0)."""
    max_len = max(len(a), len(b), 1)
    dist = Levenshtein.distance(a, b)
    return 1.0 - dist / max_len


def _score_window(query_words: list[str], window_words: list[str],
                  query_deep: list[str], window_deep: list[str]) -> float:
    """
    احسب نسبة تطابق نافذة كلمات مع استعلام المستخدم.
    نستخدم نسختين: خفيفة (أولوية) وعميقة (احتياط).
    """
    if len(window_words) != len(query_words):
        return 0.0

    total = 0.0
    for qw, ww, qd, wd in zip(query_words, window_words, query_deep, window_deep):
        s_light = _word_similarity(qw, ww)
        s_deep  = _word_similarity(qd, wd)
        total += max(s_light, s_deep)

    return total / len(query_words)


# ==========================================
# الدالة الرئيسية
# ==========================================

def search_bayan(query_text: str,
                 target_type: str = "تدقيق الايات",
                 fuzzy_threshold: float = 0.72,
                 db_path: str = None,
                 top_n: int = 1) -> dict:
    """
    البحث عن آية قرآنية مع دعم الأخطاء الإملائية.

    المعاملات:
        query_text       : النص المُدخَل من المستخدم (قد يحتوي أخطاء)
        target_type      : لغة الإخراج (uthmani / english / french / ...)
        fuzzy_threshold  : الحد الأدنى لقبول التطابق (0→1)، افتراضياً 0.72
        db_path          : مسار ملف قاعدة البيانات (افتراضياً بجوار هذا الملف)

    المُخرج:
        dict يحتوي على:
            matched_segment   : النص المُصحَّح بالرسم العثماني أو الترجمة
            full_verse        : الآيات كاملة مع التوثيق
            similarity_score  : درجة التشابه
            metadata          : تفاصيل الآيات
        أو:
            error             : رسالة الخطأ
    """
    import os
    if db_path is None:
        db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'quran_master.db')
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    language_mapping = {
        "تدقيق الايات": "uthmani",
        "bengali": "bn", "bosnian": "bs", "english": "en", "french": "fr",
        "german": "de", "indonesian": "id", "malay": "ms", "persian": "fa",
        "portuguese": "pt", "russian": "ru", "spanish": "es",
        "turkish": "tr", "uzbek": "uz"
    }

    clean_target = str(target_type).lower().strip()
    lang_code    = language_mapping.get(clean_target, "uthmani")

    verse_column = "v.text_uthmani" if lang_code == "uthmani" else f"v.lang_{lang_code}"
    sura_column  = "s.ar"           if lang_code == "uthmani" else f"s.lang_{lang_code}"

    # ── تطبيع الاستعلام بنسختين ──
    query_light = normalize_arabic(query_text, deep=False).split()
    query_deep  = normalize_arabic(query_text, deep=True).split()

    if not query_light:
        conn.close()
        return {"error": "النص المُدخل فارغ"}

    n = len(query_light)

    # ── إذا بدأ الاستعلام بالبسملة → أعطِ الفاتحة أولوية ──
    _query_starts_basmala = False
    if n >= 4:
        first4_q = normalize_arabic(' '.join(query_light[:4]), deep=False)
        if first4_q in ['بسم الله الرحمن الرحيم', 'بسم لله لرحمن لرحيم', 'بسم لله لرحمـن لرحيم']:
            _query_starts_basmala = True

    # ==========================================
    # البحث بالمرساة الديناميكية (من الأطول للأقصر)
    # ==========================================
    candidate_starts: list[tuple[int, int]] = []

    for i in range(n, 0, -1):
        anchor = ' '.join(query_light[:i])
        cursor.execute("""
            SELECT v.sura_num, v.aya_num
            FROM verses v
            WHERE v.text_clean LIKE ?
            ORDER BY v.sura_num, v.aya_num
        """, ('%' + anchor + '%',))
        candidate_starts = cursor.fetchall()
        if candidate_starts:
            break

    # إذا بدأ بالبسملة → الفاتحة أولوية
    if _query_starts_basmala:
        fatiha = (1, 1)
        if fatiha not in candidate_starts:
            candidate_starts.insert(0, fatiha)
        else:
            candidate_starts.remove(fatiha)
            candidate_starts.insert(0, fatiha)

    # إذا لم تجد شيئاً بالمرساة الخفيفة → جرّب المرساة العميقة
    if not candidate_starts:
        cursor.execute("PRAGMA table_info(verses)")
        cols = {row[1] for row in cursor.fetchall()}
        deep_col = "v.text_deep" if "text_deep" in cols else "v.text_clean"

        for i in range(n, 0, -1):
            anchor_deep = ' '.join(query_deep[:i])
            cursor.execute(f"""
                SELECT v.sura_num, v.aya_num
                FROM verses v
                WHERE {deep_col} LIKE ?
                ORDER BY v.sura_num, v.aya_num
            """, ('%' + anchor_deep + '%',))
            rows = cursor.fetchall()
            if rows:
                candidate_starts = rows
                break

    # الملاذ الأخير: ابحث بكل كلمة على حدة وخذ الآيات الأكثر تكراراً
    if not candidate_starts:
        counts: dict[tuple, int] = {}
        for word in query_light:
            if len(word) < 3:
                continue
            cursor.execute("""
                SELECT v.sura_num, v.aya_num
                FROM verses v
                WHERE v.text_clean LIKE ?
            """, ('%' + word + '%',))
            for row in cursor.fetchall():
                counts[row] = counts.get(row, 0) + 1
        if counts:
            candidate_starts = sorted(counts, key=counts.get, reverse=True)[:15]

    if not candidate_starts:
        conn.close()
        return {
            "matched_segment": "",
            "full_verse": "لم يُعثر على تطابق — تحقق من النص المُدخل"
        }

    # ==========================================
    # النافذة المنزلقة + التقييم الضبابي
    # ==========================================
    best_score     = -1.0
    best_match_idx = -1
    best_rows      = None
    all_matches    = []

    for start_sura, start_aya in candidate_starts:
        cursor.execute(f"""
            SELECT v.sura_num, v.aya_num, v.text_clean,
                   v.text_uthmani, {verse_column}, {sura_column}
            FROM verses v
            JOIN suras_translated s ON v.sura_num = s.sura_number
            WHERE (v.sura_num = ? AND v.aya_num >= ?) OR (v.sura_num > ?)
            ORDER BY v.sura_num, v.aya_num
            LIMIT 12
        """, (start_sura, start_aya, start_sura))
        fetched = cursor.fetchall()

        QURAN_MARKS = {
              'ۖ', 'ۗ', 'ۘ', 'ۙ', 'ۚ',
              'ۛ', 'ۜ', '۝', '۞', '۩'
          }

        # بناء خريطة الكلمات
        combined_light, combined_deep, word_map = [], [], []
        for row in fetched:
            s_num, a_num, t_clean, t_uthmani, t_target, s_name = row

            # ── شيل البسملة من text_clean في البحث (مش الفاتحة) ──
            if a_num == 1 and s_num != 1:
                tc_words = t_clean.split()
                if len(tc_words) >= 4:
                    first4 = normalize_arabic(' '.join(tc_words[:4]), deep=False)
                    basmala_norms = [
                        'بسم الله الرحمن الرحيم',
                        'بسم لله لرحمن لرحيم',
                        'بسم لله لرحمـن لرحيم',
                    ]
                    if first4 in basmala_norms:
                        t_clean = ' '.join(tc_words[4:])

            clean_w   = t_clean.split()
            uthmani_w = [
              token
              for token in t_uthmani.split()
              if token not in QURAN_MARKS
            ]
            deep_w    = normalize_arabic(t_clean, deep=True).split()

            for j, cw in enumerate(clean_w):
                combined_light.append(cw)
                combined_deep.append(deep_w[j] if j < len(deep_w) else cw)
                word_map.append({
                    "clean":       cw,
                    "uthmani":     uthmani_w[j] if j < len(uthmani_w) else cw,
                    "sura_num":    s_num,
                    "aya_num":     a_num,
                    "target_text": t_target,
                    "sura_name":   s_name,
                })

        total_words = len(combined_light)
        if total_words < n:
            continue

        # نافذة منزلقة
        best_cand_score = -1.0
        best_cand_idx   = -1
        for j in range(total_words - n + 1):
            score = _score_window(
                query_light, combined_light[j:j+n],
                query_deep,  combined_deep[j:j+n]
            )
            if score > best_cand_score:
                best_cand_score = score
                best_cand_idx   = j

        if best_cand_score >= fuzzy_threshold and best_cand_idx != -1:
            if best_cand_score > best_score:
                best_score     = best_cand_score
                best_match_idx = best_cand_idx
                best_rows      = word_map
            if top_n > 1:
                all_matches.append((best_cand_score, best_cand_idx, word_map))

        if best_score >= 0.999 and top_n == 1:
            break

    conn.close()

    # ==========================================
    # تشكيل المخرجات
    # ==========================================

    def to_arabic_nums(num):
        ar_digits = '٠١٢٣٤٥٦٧٨٩'
        return ''.join(ar_digits[int(d)] for d in str(num))

    def fmt_num(num):
        return to_arabic_nums(num) if lang_code == "uthmani" else str(num)

    def _strip_basmala(text):
        words = text.split()
        if len(words) < 4:
            return text
        first4_norm = normalize_arabic(' '.join(words[:4]), deep=False)
        basmala_forms = [
            'بسم الله الرحمن الرحيم',
            'بسم لله لرحمن لرحيم',
            'بسم لله لرحمـن لرحيم',
        ]
        if first4_norm in basmala_forms:
            return ' '.join(words[4:])
        return text

    def _format_one(rows, idx, score_val):
        matched_words = rows[idx: idx + n]
        if not matched_words:
            return None

        involved = {}
        for w in matched_words:
            key = (w["sura_num"], w["aya_num"])
            if key not in involved:
                involved[key] = {
                    "sura_name": w["sura_name"],
                    "target_text": w["target_text"],
                }

        sura_counts = {}
        for w in matched_words:
            sura_counts[w["sura_num"]] = sura_counts.get(w["sura_num"], 0) + 1
        p_sura = max(sura_counts, key=sura_counts.get)
        involved = {k: v for k, v in involved.items() if k[0] == p_sura}

        ayah_nums = [a for (_, a) in involved]
        s_name = next(iter(involved.values()))["sura_name"]

        verse_parts = []
        for (s_num, a_num), data in involved.items():
            txt = data['target_text']
            if a_num == 1 and s_num != 1:
                txt = _strip_basmala(txt)
            verse_parts.append(f"{txt} ({fmt_num(a_num)})")

        combined_body = " ".join(verse_parts)

        if len(ayah_nums) == 1:
            ref = f"{s_name}: {fmt_num(ayah_nums[0])}"
        else:
            ref = f"{s_name}: {fmt_num(ayah_nums[0])}-{fmt_num(ayah_nums[-1])}"

        result_text = f"({combined_body}) 【{ref}】"

        return {
            "matched_segment": result_text,
            "full_verse": result_text,
            "similarity_score": score_val,
            "sura_num": p_sura,
            "aya_start": ayah_nums[0],
        }

    # ── مسار النتيجة الواحدة (backward compat) ──
    if top_n <= 1:
        if best_score < fuzzy_threshold or best_match_idx == -1:
            return {
                "error": "لم يُعثر على تطابق كافٍ — تحقق من النص المُدخل."
            }
        return _format_one(best_rows, best_match_idx, best_score)

    # ── مسار النتائج المتعددة ──
    if not all_matches:
        return {
            "error": "لم يُعثر على تطابق كافٍ — تحقق من النص المُدخل."
        }

    # ترتيب حسب الدرجة تنازلياً + إزالة التكرار بنفس (سورة، آية)
    all_matches.sort(key=lambda x: x[0], reverse=True)
    seen_keys = set()
    unique = []
    for score_val, idx, rows in all_matches:
        result = _format_one(rows, idx, score_val)
        if result is None:
            continue
        dedup_key = (result["sura_num"], result["aya_start"])
        if dedup_key in seen_keys:
            continue
        seen_keys.add(dedup_key)
        unique.append(result)
        if len(unique) >= top_n:
            break

    if not unique:
        return {
            "error": "لم يُعثر على تطابق كافٍ — تحقق من النص المُدخل."
        }

    return {
        "matches": unique,
        "total_found": len(all_matches),
    }
